# Generated by Django 5.0.6 on 2024-06-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_remove_juego_precio_remove_pedido_juegos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='materiales',
            field=models.TextField(default='Sin especificar'),
        ),
    ]
