# Generated by Django 5.0.6 on 2024-06-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0003_juego_materiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
