# Generated by Django 5.0.6 on 2024-06-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0004_juego_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
